#!/bin/sh

mode=edit

ref=${1:?expected a git ref}
shift

if [ "$1" = -e ]; then
    mode=reword
    shift
fi

if [ "$ref" = -h ] ||
    [ "$ref" = --help ]
then
    printf 'Usage: %s <ref> [Options]\n' "${0##*/}"
    echo 'Editing target commit'
    echo
    echo 'Options:'
    echo '    -e        Use reword instead of edit'
    exit
fi

ref=$(git rev-parse --short "$ref") || exit

if ! git merge-base --is-ancestor "$ref" HEAD; then
    echo "${0##*/}: HEAD not contains $ref"
    exit 2
fi

git -c advice.waitingForEditor=false \
    -c sequence.editor="sed -Ei '/^pick +$ref/s/^pick/$mode/'" \
    rebase -i "$ref^" "$@"
