#!/bin/bash
set -o pipefail
if [ $# != 0 ]; then
    printf '%q: unexpected arg %s\n' "${0##*/}" "${1@Q}" >&2
    exit 2
fi
cur=$(git branch --show-current) || exit
git for-each-ref 'refs/heads/*' --merged HEAD --format='%(refname:strip=2)' | while read -r; do
    [ "$REPLY" != "$cur" ] && git branch -d "$REPLY"
done
