#!/usr/bin/bash
set -o nounset
set -o errtrace
set -o pipefail
function CATCH_ERROR { # {{{
    local __LEC=$? __i __j
    set +x
    echo "Traceback (most recent call last):" >&2
    for ((__i = ${#FUNCNAME[@]} - 1; __i >= 0; --__i)); do
        printf '  File %q line %s in %q\n' >&2 \
            "${BASH_SOURCE[__i]}" \
            "${BASH_LINENO[__i]}" \
            "${FUNCNAME[__i]}"
        if ((BASH_LINENO[__i])) && [ -f "${BASH_SOURCE[__i]}" ]; then
            for ((__j = 0; __j < BASH_LINENO[__i]; ++__j)); do
                read -r REPLY
            done < "${BASH_SOURCE[__i]}"
            printf '    %s\n' "$REPLY" >&2
        fi
    done
    echo "Error: [ExitCode: ${__LEC}]" >&2
    exit "${__LEC}"
}
trap CATCH_ERROR ERR # }}}

hash gh jq mktemp cat

if [[ $# = 1 && $1 = -h ]]; then
    printf 'Usage: %q <reviewer> [-d] [args]..\n' "${0##*/}"
    echo 'Request review'
    exit
fi

req_opts=(--json url)

if [ -t 0 ] && [ -t 2 ] && [ -z "${1-}" ]; then
    req_opts+=(--json reviews)
else
    reviewer=${1?required a reviewer arg}
fi
method=POST
shift

args=()
for arg; do case "$arg" in
    -d) method=DELETE;;
    *) args+=("$arg");;
esac done

meta=$(gh pr view "${req_opts[@]}" "${args[@]}" |
    jq -r '.url, ([.reviews[]?.author.login] | unique[])' || exit)
mapfile -t meta <<< "$meta"

url=${meta[0]}
number=${url##*/}
api=/repos${url##*github.com}
api=${api%pull/*?}pulls/$number/requested_reviewers
echo "${api@A}" >&2

PS3="request reviewer> "; select reviewer in "${meta[@]:1}"; do
    [ -n "$reviewer" ] && break
    echo 'Invalid reviewer' >&2
done || exit

gh api --method $method \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "$api" \
    --input <(jq -R '{reviewers:[.]}' <<< "$reviewer") |
    jq -r '["Reviewers:", "• "+.requested_reviewers[].login]? |.[]' || exit
