#!/usr/bin/bash
set -o nounset
set -o errtrace
set -o pipefail
function CATCH_ERROR { # {{{
    local __LEC=$? __i __j
    set +x
    echo "Traceback (most recent call last):" >&2
    for ((__i = ${#FUNCNAME[@]} - 1; __i >= 0; --__i)); do
        printf '  File %q line %s in %q\n' >&2 \
            "${BASH_SOURCE[__i]}" \
            "${BASH_LINENO[__i]}" \
            "${FUNCNAME[__i]}"
        if ((BASH_LINENO[__i])) && [ -f "${BASH_SOURCE[__i]}" ]; then
            for ((__j = 0; __j < BASH_LINENO[__i]; ++__j)); do
                read -r REPLY
            done < "${BASH_SOURCE[__i]}"
            printf '    %s\n' "$REPLY" >&2
        fi
    done
    echo "Error: [ExitCode: ${__LEC}]" >&2
    exit "${__LEC}"
}
trap CATCH_ERROR ERR # }}}

hash gh jq awk mktemp

unset body body_file

args=()
OPTIND=1
while case "${!OPTIND---}" in
    -*?)false;;
    *)  args+=("${!OPTIND}"); ((++OPTIND)); continue
esac || getopts h-f: opt; do case "$opt" in
    h|-)
        printf 'Usage: %q [Options] <comment_url>\n' "${0##*/}"
        echo 'Replies review comment'
        echo
        printf '%s\n' \
            'Options:' \
            '    -f <file>          comment body from file' \
            '    -h                 show help' \
            && exit
        ;;
    f) body_file=$OPTARG;;
    :|\?)
        ((--OPTIND <= 0)) && OPTIND=1
        printf '%q: parse args failed, near by %q\n' "$0" "${!OPTIND}" >&2
        exit 2
esac done
set -- "${args[@]}" "${@:OPTIND}"

if [ $# -eq 0 ]; then
    printf '%q: expected a arg\n' "$0" >&2
    exit 2
fi
if [ $# -ne 1 ]; then
    printf '%q: unexpected arg %q\n' "$0" "$2" >&2
    exit 2
fi

api=$(jq -Rrs <<< "$1" '
sub("\\s*$"; "") |
capture("^\\s*
  (https?://)?github\\.com/
  (?<owner>[^/]+)/
  (?<repo>[^/]+)/
  pull/
  (?<number>[^#/]+)
  \\#discussion_r
  (?<id>\\d+)
  \\s*$";
"x") // error("Invalid comment url: \(@sh)")
| "/repos/\(.owner)/\(.repo)/pulls/\(.number)/comments/\(.id)/replies"
') || exit
echo "${api@A}" >&2

tmp=$(mktemp review-replies.XXXXXXXXXX)
# shellcheck disable=2064
trap "echo Aborted, replies-file: ${tmp@Q}" exit

if [ -v body_file ]; then
    cat -- "$body_file" > "$tmp"
else
    "${EDITOR:-/usr/bin/vim}" "$tmp"
fi

body=$(<"$tmp")

test -n "$body" # replies body by empty

gh api --method POST \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "$api" \
    -f "body=$body" | jq 'select(.user? // false | not)'

rm "$tmp"
trap '' exit
