#!/usr/bin/bash
set -o nounset
set -o errtrace
set -o pipefail
function CATCH_ERROR { # {{{
    local __LEC=$? __i __j
    set +x
    echo "Traceback (most recent call last):" >&2
    for ((__i = ${#FUNCNAME[@]} - 1; __i >= 0; --__i)); do
        printf '  File %q line %s in %q\n' >&2 \
            "${BASH_SOURCE[__i]}" \
            "${BASH_LINENO[__i]}" \
            "${FUNCNAME[__i]}"
        if ((BASH_LINENO[__i])) && [ -f "${BASH_SOURCE[__i]}" ]; then
            for ((__j = 0; __j < BASH_LINENO[__i]; ++__j)); do
                read -r REPLY
            done < "${BASH_SOURCE[__i]}"
            printf '    %s\n' "$REPLY" >&2
        fi
    done
    echo "Error: [ExitCode: ${__LEC}]" >&2
    exit "${__LEC}"
}
trap CATCH_ERROR ERR # }}}

case $* in -h|--help)
    gh pr list "$@"
    exit
esac

gh pr list "$@" \
    --json title \
    --json number \
    --json mergeable \
    --json statusCheckRollup \
    --json state \
    --json isDraft \
    --json reviewDecision \
| jq -r '
def csim(seq): [seq]|"\u001b[\(join(";"))m";
def csim: csim(empty);
def short($n): if length > $n then .[:$n-3]+"..." end;
def fi($n): tostring | " "*($n-length)+.;

(max_by(.number).number|@text|length) as $numw
| .[]
| ( if .statusCheckRollup | any(.conclusion == "FAILURE") then
    "!"
  elif .mergeable == "CONFLICTING" then
    "λ"
  elif .reviewDecision == "CHANGES_REQUESTED" then
    "*"
  else
    " "
  end) as $icon
| (if .isDraft or .state != "OPEN" then csim(38,5,238) else "" end) as $color
| $color+$icon+csim(2)+(.number|fi($numw))+csim(22)+" "+(.title|short(85))+csim
'
