#!/usr/bin/bash
set -o nounset
set -o errtrace
set -o pipefail
function CATCH_ERROR { # {{{
    local __LEC=$? __i __j
    set +x
    echo "Traceback (most recent call last):" >&2
    for ((__i = ${#FUNCNAME[@]} - 1; __i >= 0; --__i)); do
        printf '  File %q line %s in %q\n' >&2 \
            "${BASH_SOURCE[__i]}" \
            "${BASH_LINENO[__i]}" \
            "${FUNCNAME[__i]}"
        if ((BASH_LINENO[__i])) && [ -f "${BASH_SOURCE[__i]}" ]; then
            for ((__j = 0; __j < BASH_LINENO[__i]; ++__j)); do
                read -r REPLY
            done < "${BASH_SOURCE[__i]}"
            printf '    %s\n' "$REPLY" >&2
        fi
    done
    echo "Error: [ExitCode: ${__LEC}]" >&2
    exit "${__LEC}"
}
trap CATCH_ERROR ERR # }}}

hash gh jq mktemp cat

if [[ $# = 1 && $1 = -h ]]; then
    printf 'Usage: %q <reviewer> [args]..\n' "${0##*/}"
    echo 'Request review'
    exit
fi

reviewer=${1?expected a reviewer arg}
method=POST
shift

args=()
for arg; do case "$arg" in
    -d) method=DELETE;;
    *) args+=("$arg");;
esac done

url=$(gh pr view --json url "${args[@]}" | jq -r .url || exit)
number=${url##*/}
api=/repos${url##*github.com}
api=${api%pull/*?}pulls/$number/requested_reviewers
echo "${api@A}" >&2

gh api --method $method \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "$api" \
    --input <(jq -R '{reviewers:[.]}' <<< "$reviewer") |
    jq -r '["Reviewers:", "• "+.requested_reviewers[].login]?[]' || exit
