#!/usr/bin/bash
set -o nounset
set -o errtrace
set -o pipefail

json_options=(
    --json assignees
    --json author
    --json closedByPullRequestsReferences
    --json comments
    --json createdAt
    --json labels
    --json number
    --json title
    --json updatedAt
    --json url
)

hash stty || exit

info=$(stty -a || echo 80)
cols=${info##*columns }
cols=${cols%%;*}

gh issue list "${json_options[@]}" "$@" |
#< result \
    jq -sRr --argjson col "$cols" '
fromjson? // halt_error(1) |
"│ " as $L |
def fi($n): tostring | .+" "*($n-length);
def elap:
  [
    (now, fromdate)
    | strftime("%s")
    | tonumber
  ]
  | first-last
  | [
      ., (
        ./60 | ., (
          ./60 | ., (
            ./24 | ., (
              ./30.4375 | ., (
                ./12)))))
      | floor
    ]
  | [" seconds", "min", "h", "d", "mon", "year"] as $label
  | last(to_entries[]
    | [.value, $label[.key]]
    | select(first > 1)
    | join("")
  )
  ;
def short($n): if length > $n then .[:$n-3]+"..." end;
def state:
  if .closedByPullRequestsReferences | length != 0 then
    "P"
  elif .assignees | length != 0 then
    "A"
  else
    " "
  end
  ;
def say: .comments | length | "^"+@text | if .[1:] == "0" then "" end;
.[] |= (.number |= @text
       |.labels |= (map(.name) | join(" ") | short(30))
       |.meta = (.createdAt | elap)+say
       ) |
(map(.number | length+1) | max) as $numlen |
(map(.labels | length+1) | max) as $lablen |
(map(.meta | length+1) | max) as $metalen |
.[] |
state
  +(.number | fi($numlen))
  +(.labels | fi($lablen))
  +$L+"\(.meta|fi($metalen))"+$L+.title |
.[:$col]
'
