#!/usr/bin/bash
set -o nounset
set -o errtrace
#set -o pipefail
function CATCH_ERROR { # {{{
    local __LEC=$? __i __j
    echo "Traceback (most recent call last):" >&2
    for ((__i = ${#FUNCNAME[@]} - 1; __i >= 0; --__i)); do
        printf '  File %q line %s in %q\n' >&2 \
            "${BASH_SOURCE[__i]}" \
            "${BASH_LINENO[__i]}" \
            "${FUNCNAME[__i]}"
        if ((BASH_LINENO[__i])) && [ -f "${BASH_SOURCE[__i]}" ]; then
            for ((__j = 0; __j < BASH_LINENO[__i]; ++__j)); do
                read -r REPLY
            done < "${BASH_SOURCE[__i]}"
            printf '    %s\n' "$REPLY" >&2
        fi
    done
    echo "Error: [ExitCode: ${__LEC}]" >&2
    exit "${__LEC}"
}
trap CATCH_ERROR ERR # }}}

function run { # {{{
    local arg
    printf '==> %q' "$1"
    for arg in "${@:2}"; do
        printf ' %s' "${arg@Q}"
    done
    echo
    "$@"
} # }}}

shopt -s nullglob

clean=''
rename_to=''
default='fn main() {}'
proj=~/Project/Rust/quick-rs
bin=$proj/src/bin

args=()
OPTIND=1
while case "${!OPTIND---}" in
    -*?)false;;
    *)  args+=("${!OPTIND}"); ((++OPTIND)); continue
esac || getopts hpr:cd:l opt; do case "$opt" in
    h)
        printf 'Usage: %q [Options] name\n' "${0##*/}"
        echo 'Quick edit .rs single file'
        echo
        printf '%s\n' \
            'Options:' \
            '    -p                 init quick-rs project' \
            '    -r <name>          rename to name, and edit new file' \
            '    -c                 clean default files and target' \
            '    -d <default>       set default src' \
            '    -l                 list files' \
            '    -h                 show help' \
            && exit
        ;;
    c) clean=1;;
    r) rename_to=$OPTARG;;
    d) default=$OPTARG;;
    l) ls -- "$bin"; exit;;
    p)
        hash cargo realpath sed rm mkdir
        run cargo new quick-rs
        run cd -- "$_" || exit
        run sed -i '/^edition/a default-run = ""' Cargo.toml
        run mkdir src/bin
        run rm src/main.rs
        echo "Update this script proj=... to proj=${PWD@Q}"
        exit
        ;;
    :|\?)
        ((--OPTIND <= 0)) && OPTIND=1
        printf '%q: parse args failed, near by %q\n' "$0" "${!OPTIND}" >&2
        exit 2
esac done
set -- "${args[@]}" "${@:OPTIND}"
if [ $# -gt 1 ]; then
    printf '%q: unexpected arg %q\n' "$0" "$2" >&2
    exit 2
fi

editor=${VISUAL-${EDITOR-vim}}

hash sed "$editor" mv

name=${1:-main}

f=$bin/$name.rs

run cd -- "$proj" || exit

if [ -n "$clean" ]; then
    echo 'Cleaning ...'
    run cargo clean || :

    for file in "$bin"/*; do
        file_text=$(< "$file")
        test "$file_text" = "$default" && run rm -- "$file"
    done
fi

run sed -i "/^default-run/c default-run = \"$name\"" Cargo.toml

test -n "$rename_to" && run mv -vi -- "$f" "$bin/${rename_to%.rs}.rs"
test -e "$f" || echo "$default" > "$f"

run "$editor" "$f"
