#!/usr/bin/bash

arg_input=''
empty_newline=''
prelude=''
REPLY=''

unset input

OPTIND=1
while getopts aAI:i:f:eh opt; do case "$opt" in
    a) arg_input=first;;
    A) arg_input=last;;
    i) REPLY=$OPTARG;;
    I) prelude=$OPTARG;;
    f) input=$(< "$OPTARG");;
    e) empty_newline=1;;
    h)
        printf 'Usage: %q [Options] <command> [args...]\n' "${0##*/}"
        echo 'REPL input command'
        printf 'Example: %q -a jq -n\n' "${0##*/}"
        echo
        printf '%s\n' \
            'Options:' \
            '    -a                 use first arg input' \
            '    -A                 use last arg input' \
            '    -i <text>          like read -i, readline init text' \
            '    -I <text>          like -i, but no readline and history' \
            '    -f <file>          stdin from file' \
            '    -e                 empty new line' \
            '    -h                 show help' \
            && exit
        ;;
    :|\?)
        ((--OPTIND <= 0)) && OPTIND=1
        printf '%q: parse args failed, near by %q\n' "$0" "${!OPTIND}" >&2
        exit 2
esac done
set -- "${@:OPTIND}"
cmd=${1?parse args failed, expected a arg}
shift
printf -v prompt '%q' "$cmd"
prompt+='> '

printf 'REPL for %q' "$cmd"
[ $# -ne 0 ] && printf ' %q' "$@"
echo

HISTFILE=~/.replline_history
touch -- "$HISTFILE" \
    && history -r \
    || exit
trap 'history -w' exit

exitcode=0

prev=$REPLY

function run { # {{{
    if [ "$arg_input" = first ]; then
        "$cmd" "$input" "$@"
    elif [ "$arg_input" = last ]; then
        "$cmd" "$@" "$input"
    else
        "$cmd" "$@" <<< "$input"
    fi
} # }}}

while printf '\e[1m'; read -rep "$prompt" -i "$REPLY"; do
    printf '\e[m'

    [ "$prev" != "$REPLY" ] && history -s -- "$REPLY"
    prev=$REPLY
    input=$prelude$REPLY

    if [ -v input ]; then
        run "$@" <<< "$input"
    else
        run "$@"
    fi
    exitcode=$?
    [ $exitcode -ne 0 ] && echo $'\n'"exit code: $exitcode" >&2
    [ -n "$empty_newline" ] && REPLY=''
done

echo
exit $exitcode
